- include_tasks: install.yml
  with_items:
    - libestr-0.1.11-1.ipfire
    - libfastjson-0.99.8-1.ipfire
    - liblogging-1.0.6-1.ipfire
    - rsyslog-8.1907.0-1.ipfire
  vars:
    packet: "{{ item }}"
