---
- name: Create C:\Temp directory
  win_file:
    path: C:\Temp
    state: directory

- name: Upload assets to the client
  win_copy:
    src: files/win10_assets/assets.zip
    dest: C:\Temp\assets.zip

- name: Extract assets to the C:\BREACH folder
  win_unzip:
    src: C:\Temp\assets.zip
    dest: C:\BREACH
    creates: C:\BREACH

- name: Upload init_tbf_client.py to the client
  win_copy:
    src: files/win10_assets/init_tbf_client.py
    dest: C:\BREACH\init_tbf_client.py

- name: Upload run_userbehavior.py to the client
  win_copy:
    src: files/win10_assets/run_userbehavior.py
    dest: C:\BREACH\run_userbehavior.py

- name: Upload geckodriver 0.31.0 to the client
  win_copy:
    src: files/win10_assets/geckodriver.exe
    dest: C:\Python37

- name: Allow all users the write permission for C:\BREACH folder (for logs)
  win_acl:
    path: C:\BREACH
    user: Users
    rights: Write
    type: allow
    state: present

